using System.Collections.Generic;
using DodgeballUltra.AI;
using DodgeballUltra.Characters;
using DodgeballUltra.Juice;
using UnityEngine;

namespace DodgeballUltra.Match
{
    /// <summary>
    /// Root configuration asset referenced by the Arena scene's GameBootstrap. Generated by the Setup Wizard at
    /// Assets/DodgeballUltra/Generated/Data/GameConfig.asset. If missing, GameBootstrap builds an in-memory default.
    /// </summary>
    [CreateAssetMenu(fileName = "GameConfig", menuName = "Dodgeball Ultra/Game Config", order = 1)]
    public sealed class GameConfig : ScriptableObject
    {
        [Tooltip("The ten heroes (order = hero select grid).")]
        public List<CharacterData> roster = new List<CharacterData>();
        public MatchRules rules;
        public JuiceProfile juice;
        public BotDifficulty defaultDifficulty = BotDifficulty.Normal;

        [Header("Ball look")]
        [Tooltip("Optional material for match balls (realistic textured foam). Generated if empty.")]
        public Material ballMaterial;
        [Tooltip("Optional prefab overriding the procedural ball visual (must not contain colliders).")]
        public GameObject ballVisualPrefab;

        public CharacterData GetHero(HeroId hero)
        {
            for (int i = 0; i < roster.Count; i++)
                if (roster[i] != null && roster[i].heroId == hero) return roster[i];
            return null;
        }
    }
}
